### PR TITLE
Update golang and alpine versions of go base image

### PR DESCRIPTION
**Pull request by efabens**

### CODE REVIEW

**Review by galxy25 — APPROVED** [review]

**Review by rosasck — APPROVED** [review]

**Review by Mrhea — APPROVED** [review]

**Comment by sjonz** [comment]
Looking at the breaking change in alpine 3.14. Do we have a sense of how big the lift is to get there, or is it an unknown?

**Comment by efabens** [comment]
3.14 was released a few hours after I pushed this commit, and the go image was just pushed late yesterday. Makes sense to update to the last. I am not seeing any breaking changes listed in the 3.14 release notes that would conflict with this image.

**Comment by efabens** [comment]
Now I see the potential breaking change. We will need to test that against our infrastructure and see what version of moby we are running before making the jump to 3.14

**Comment by galxy25** [comment]
@efabens any particular reason we need or want 1.16.5 vs a more vanilla (and hopefully less breaking) 1.16-alpine tag?

**Comment by efabens** [comment]
With go, given its backwards compatibility promises, 1.16 is probably ok. I do think we want to stick with alpine3.13.

**Pull request merged**
